// SPDX-License-Identifier: MIT
// Generated by portable/generate.py. Edit portable/catalog.json instead.
package com.deskport.core;

public final class DPCatalog {
    private DPCatalog() {}
    public static final int BASE_PORT = 48989;
    public static final int PORT_STEP = 100;
    public static final int PORT_COUNT = 20;
    public static final int CONTROL_OFFSET = 2;
    public static final int BINDING_PORT = 48991;
    public static final int TUNING_COUNT = 10;
    public static final int TUNING_DEFAULT_INDEX = 5;
    public static final int DISPLAY_POLICY_VERSION = 1;
    public static final int POLICY_PRIMARY_MIRROR = 0;
    public static final int POLICY_PRIMARY_ONLY = 1;
    public static final int POLICY_EXTEND = 2;
    public static final int POLICY_DEFAULT = 0;
    private static final double[] TUNING = {0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.3, 1.4, 1.5};
    private static final String[] LABELS = {"0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.2", "1.3", "1.4", "1.5"};
    public static double[] tuningValues() { return TUNING.clone(); }
    public static String[] tuningLabels() { return LABELS.clone(); }
    public static boolean isBasePort(int port) {
        if (port < BASE_PORT || port > 65535) return false;
        int delta = port - BASE_PORT;
        return delta / PORT_STEP < PORT_COUNT && delta % PORT_STEP == 0;
    }
    public static int controlPort(int base) { return isBasePort(base) ? base + CONTROL_OFFSET : 0; }
    public static boolean displayPolicyValid(int value) {
        return value == POLICY_PRIMARY_MIRROR || value == POLICY_PRIMARY_ONLY || value == POLICY_EXTEND;
    }
}
