// SPDX-License-Identifier: MIT
// Generated by portable/generate.py. Edit portable/catalog.json instead.
#ifndef DESKPORT_CATALOG_H
#define DESKPORT_CATALOG_H
#define DP_CATALOG_BASE_PORT 48989
#define DP_CATALOG_PORT_STEP 100
#define DP_CATALOG_PORT_COUNT 20
#define DP_CATALOG_CONTROL_OFFSET 2
#define DP_CATALOG_BINDING_PORT 48991
#define DP_CATALOG_TUNING_COUNT 10
#define DP_CATALOG_TUNING_DEFAULT_INDEX 5
#define DP_CATALOG_DISPLAY_POLICY_VERSION 1
#define DP_CATALOG_POLICY_PRIMARY_MIRROR 0
#define DP_CATALOG_POLICY_PRIMARY_ONLY 1
#define DP_CATALOG_POLICY_EXTEND 2
#define DP_CATALOG_POLICY_DEFAULT 0
static const double dp_catalog_tuning_values[] = {0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.2, 1.3, 1.4, 1.5};
static const char *const dp_catalog_tuning_labels[] = {"0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.2", "1.3", "1.4", "1.5"};
static inline int dp_catalog_is_base_port(int port) {
    if (port < DP_CATALOG_BASE_PORT || port > 65535) return 0;
    const int delta = port - DP_CATALOG_BASE_PORT;
    return delta / DP_CATALOG_PORT_STEP < DP_CATALOG_PORT_COUNT && delta % DP_CATALOG_PORT_STEP == 0;
}
// Zero denotes an invalid endpoint; never silently route to the default host.
static inline int dp_catalog_control_port(int base) {
    return dp_catalog_is_base_port(base) ? base + DP_CATALOG_CONTROL_OFFSET : 0;
}
static inline int dp_catalog_display_policy_valid(int value) {
    return value == DP_CATALOG_POLICY_PRIMARY_MIRROR || value == DP_CATALOG_POLICY_PRIMARY_ONLY || value == DP_CATALOG_POLICY_EXTEND;
}
#endif
