#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate dependency-free C and Java rules from the public product catalog."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def outputs():
    data = json.loads((ROOT / 'catalog.json').read_text())
    if data['schemaVersion'] != 1 or data['license'] != 'MIT':
        raise ValueError('Unsupported catalog schema or license')
    net, tuning, policy = (data[k] for k in ('network', 'desktopTuning', 'displayPolicy'))
    assert all(type(v) is int for v in net.values())
    assert net['basePort'] > 0 and net['portStep'] > 0 and net['portCount'] > 0
    assert 0 < net['controlOffset'] < net['portStep']
    assert net['basePort'] + (net['portCount'] - 1) * net['portStep'] + net['controlOffset'] <= 65535
    assert tuning['values'] == sorted(set(tuning['values'])) and tuning['default'] in tuning['values']
    assert all(0 < x <= 10 for x in tuning['values'])
    assert len(set(policy['values'].values())) == len(policy['values'])
    numbers = ', '.join(f'{v:.1f}' for v in tuning['values'])
    labels = ', '.join(json.dumps(f'{v:.1f}') for v in tuning['values'])
    constants = {'BASE_PORT': net['basePort'], 'PORT_STEP': net['portStep'], 'PORT_COUNT': net['portCount'],
                 'CONTROL_OFFSET': net['controlOffset'], 'TUNING_COUNT': len(tuning['values']),
                 'TUNING_DEFAULT_INDEX': tuning['values'].index(tuning['default']),
                 'DISPLAY_POLICY_VERSION': policy['version']}
    constants.update({'POLICY_' + k: v for k, v in policy['values'].items()})
    constants['POLICY_DEFAULT'] = policy['values'][policy['default']]
    c = '''// SPDX-License-Identifier: MIT
// Generated by portable/generate.py. Edit portable/catalog.json instead.
#ifndef DESKPORT_CATALOG_H
#define DESKPORT_CATALOG_H
'''
    c += '\n'.join(f'#define DP_CATALOG_{k} {v}' for k, v in constants.items()) + '\n'
    c += f'''static const double dp_catalog_tuning_values[] = {{{numbers}}};
static const char *const dp_catalog_tuning_labels[] = {{{labels}}};
static inline int dp_catalog_is_base_port(int port) {{
    if (port < DP_CATALOG_BASE_PORT || port > 65535) return 0;
    const int delta = port - DP_CATALOG_BASE_PORT;
    return delta / DP_CATALOG_PORT_STEP < DP_CATALOG_PORT_COUNT && delta % DP_CATALOG_PORT_STEP == 0;
}}
// Zero denotes an invalid endpoint; never silently route to the default host.
static inline int dp_catalog_control_port(int base) {{
    return dp_catalog_is_base_port(base) ? base + DP_CATALOG_CONTROL_OFFSET : 0;
}}
static inline int dp_catalog_display_policy_valid(int value) {{
    return {' || '.join('value == DP_CATALOG_POLICY_' + k for k in policy['values'])};
}}
#endif
'''
    java = '''// SPDX-License-Identifier: MIT
// Generated by portable/generate.py. Edit portable/catalog.json instead.
package com.deskport.core;

public final class DPCatalog {
    private DPCatalog() {}
'''
    java += '\n'.join(f'    public static final int {k} = {v};' for k, v in constants.items()) + '\n'
    java += f'''    private static final double[] TUNING = {{{numbers}}};
    private static final String[] LABELS = {{{labels}}};
    public static double[] tuningValues() {{ return TUNING.clone(); }}
    public static String[] tuningLabels() {{ return LABELS.clone(); }}
    public static boolean isBasePort(int port) {{
        if (port < BASE_PORT || port > 65535) return false;
        int delta = port - BASE_PORT;
        return delta / PORT_STEP < PORT_COUNT && delta % PORT_STEP == 0;
    }}
    public static int controlPort(int base) {{ return isBasePort(base) ? base + CONTROL_OFFSET : 0; }}
    public static boolean displayPolicyValid(int value) {{
        return {' || '.join('value == POLICY_' + k for k in policy['values'])};
    }}
}}
'''
    return {ROOT / 'include/deskport/catalog.h': c, ROOT / 'java/com/deskport/core/DPCatalog.java': java}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'Stale generated catalog: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == '__main__':
    main()
